### ISSUE TITLE
How to update patterns and support new languages

### ISSUE THREAD

**Issue by DumboJetEngine** [alkozko/NHyphenator#3]
Hello there! :)

I am totally new on hyphenation and I was wondering about two things:

1) Where are the files in the Resources folder of your project coming from? I took a look here : [http://tug.org/tex-hyphen/](http://tug.org/tex-hyphen/) , and it seems that the links on that table of languages point to TEX files with different content. How do we convert those to your TXT format?

2) Is it possible to support other languages with your code?

Thanks. :)

**Comment by DumboJetEngine** [comment]
After looking inside both of the file formats, I would -quite safely- speculate that you just need to copy the contents of `\hyphenation{}` to the `hyph-***.hyp.txt` file and the contents of `\patterns{}` to the `hyph-***.pat.txt` file.
Hm... Not much work to build a parser for that...

**Comment by alkozko** [comment]
Hello! Sory for delay.
Previously, library was aimed to handle only Russian and English texts and because it, we didn't need provide way for add languages without code modification.

I added new mechanism for load patterns. Now, you can create own class that implement `IHyphenatePatternsLoader` for provide patterns and exceptions for Hyphenator

You can find patterns here https://github.com/hyphenation/tex-hyphen/tree/master/hyph-utf8/tex/generic/hyph-utf8/patterns/txt
*.pat.txt files contain patterns
*.hyp.txt files contain exceptions

I will update readme file as well, for provide example
